import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import VerticalText from '../components/VerticalText/VerticalText'

export default function Home() {
	return (
		<>
			<Head>
				<title>Frogner Bygg Service</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main className={styles.main}>
				<section className={styles.heroSection}>
					<h1 className={styles.heroTitle}>Frogner Bygg Service</h1>
					<h1 className={styles.heroSubTitle}>Solid partner innen bygg</h1>
				</section>
				<VerticalText />
			</main>
		</>
	)
}
