import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Frogner Bygg Service</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
        <div className={styles.container}><h1>Frogner bygg service</h1></div>
        <div className={styles.container}><h1>kitas konteineris</h1></div>
        <div className={styles.container}><p>Footer</p></div>
      </main>

      
    </>
  )
}
